'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const faqs = [
  {
    q: 'How does TuberAI handle 10-hour videos without voice drift?',
    a: 'TuberAI uses a custom chaptered voice engine that maintains consistent pitch, pacing, and acoustic characteristics across multi-hour jobs. Unlike shorter video tools that drift after 30 minutes, your voice narrator stays identical from minute 1 to hour 10.',
  },
  {
    q: 'Can I clone my own voice for narration?',
    a: 'Yes! You can upload a 5 to 10 minute audio sample to clone your voice. TuberAI will use your voice profile to narrate your long-form YouTube videos and illustrated e-books.',
  },
  {
    q: 'Are the visuals generated by AI or stock loops?',
    a: 'TuberAI generates unique, scene-matched visual stills and cinematic frames tailored to every single paragraph of your script. There are no repetitive 5-second stock loops.',
  },
  {
    q: 'What happens if a video render fails?',
    a: 'If any render fails or encounters an error, your credits are automatically refunded to your balance immediately. You only pay for successful renders.',
  },
  {
    q: 'Can I export the script as an illustrated book or PDF?',
    a: 'Yes! TuberAI includes a built-in book generator. The same topic prompt that creates your video can also produce a print-ready PDF e-book complete with chapter headers and illustration placement for Amazon KDP or Gumroad.',
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section className="py-20 bg-transparent border-t border-[#172B33]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center mb-14">
          <div className="badge-indigo mb-4">
            <span>FAQ</span>
          </div>
          <h2 className="text-3xl sm:text-4xl md:text-2xl font-bold font-serif-heading text-[#E6F3F7] mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-[#060F12]ase text-[#7FA0AB]">
            Everything you need to know about long-form AI video generation.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={faq.q}
                className="bg-[#0E1B20] border border-[#172B33] rounded-2xl overflow-hidden shadow-2xs transition-all"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : index)}
                  className="w-full p-6 text-left flex items-center justify-between gap-4 font-bold font-serif-heading text-lg text-[#E6F3F7] hover:text-[#8FE1F4] transition-colors"
                >
                  <span>{faq.q}</span>
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 transition-transform ${isOpen ? 'bg-[#8FE1F4] text-[#060F12] rotate-180' : 'bg-[#8FE1F4]/10 text-[#8FE1F4]'}`}>
                    <ChevronDown className="w-4 h-4" />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-6 pb-6 pt-0 text-sm text-[#7FA0AB] leading-relaxed border-t border-[#060F12]">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
